### ISSUE TITLE
#1 : webflux에 대해 공부하기

### ISSUE THREAD

**Issue by mmkseoj** [telework-freaks/ondolbang-v2-technote#1]

**Comment by rudy3091** [comment]
Hello

**Comment by mmkseoj** [comment]
webflux와 R2DBC를 이용하여 백엔드를 구성하려고 시도하였으나 JPA를 사용해야 INSERT명령이 작동된다.
JPA를 사용하지 않고 INSERT를 사용할 수 있는 방법을 찾지 못하여 webflux 사용을 포기하고 Spring MVC를 사용하기로 하였다.
